const mongoose = require('mongoose');
const Exercise = require('./models/exercise');
const Diet = require('./models/diet');

mongoose.connect('mongodb://localhost:27017/fitnessApp', { useNewUrlParser: true, useUnifiedTopology: true });

const exercises = [
    {
            name: "Ходьба",
            description: "Ходьба на місці: 3 підходи по 5 хвилин.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Розтяжка рук",
            description: "Розтяжка рук: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Віджимання",
            description: "Віджимання від стіни: 2 підходи по 8 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Рухи плечима",
            description: "Кругові рухи плечима: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Планка",
            description: "Планка на колінах: 3 підходи по 20 секунд.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вбік: 3 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Нахили тулуба",
            description: "Нахили тулуба вперед: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Скручування тулуба",
            description: "Скручування тулуба на стільці: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Легка йога",
            description: "Легка йога (сонячний привіт): 3 підходи по 5 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Легка ходьба",
            description: "Легка ходьба або біг: 3 підходи по 10 хвилин.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Віджимання від стіни",
            description: "Віджимання від стіни: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Присідання",
            description: "Присідання без ваги: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 15 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вперед: 3 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Планка",
            description: "Планка: 3 підходи по 30 секунд.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Розтяжка спини",
            description: "Розтяжка спини: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Рухи руками",
            description: "Кругові рухи руками: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Нахили тулуба",
            description: "Нахили тулуба вбік: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Скручування на підлозі",
            description: "Скручування на підлозі: 3 підходи по 15 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Біг",
            description: "Біг підтюпцем: 3 підходи по 15 хвилин.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Присідання",
            description: "Присідання: 3 підходи по 15 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Віджимання",
            description: "Віджимання: 3 підходи по 12 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 20 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Планка",
            description: "Планка: 3 підходи по 45 секунд.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами назад: 3 підходи по 15 повторень на кожну ногу.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Скручування на підлозі",
            description: "Скручування на підлозі: 3 підходи по 20 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Берпі",
            description: "Берпі: 3 підходи по 10 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Випади",
            description: "Випади: 3 підходи по 15 повторень на кожну ногу.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом на носки",
            description: "Підйом на носки стоячи: 3 підходи по 15 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Ходьба на місці",
            description: "Ходьба на місці з високим підніманням колін: 3 підходи по 10 хвилин.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Присідання",
            description: "Присідання: 3 підходи по 12 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Віджимання",
            description: "Віджимання від колін: 3 підходи по 10 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 15 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Планка",
            description: "Планка: 3 підходи по 30 секунд.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вбік: 3 підходи по 12 повторень на кожну ногу.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Скручування на підлозі",
            description: "Скручування на підлозі: 3 підходи по 15 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Кроки вбік",
            description: "Кроки вбік: 3 підходи по 15 повторень на кожну ногу.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Розтяжка спини",
            description: "Розтяжка спини: 3 підходи по 10 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Випади",
            description: "Випади з підтримкою стіни: 3 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Ходьба",
            description: "Ходьба на місці з низьким підніманням колін: 3 підходи по 10 хвилин.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Присідання",
            description: "Присідання до стільця: 3 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Віджимання",
            description: "Віджимання від стіни: 3 підходи по 8 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Планка",
            description: "Планка на колінах: 3 підходи по 20 секунд.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вбік: 3 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Розтяжка рук",
            description: "Розтяжка рук: 3 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Нахили тулуба",
            description: "Нахили тулуба вперед: 3 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Рухи плечима",
            description: "Кругові рухи плечима: 3 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Легка йога",
            description: "Легка йога (сонячний привіт): 3 підходи по 5 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Жим гантелей лежачи",
            description: "Жим гантелей лежачи (2-4 кг): 3 підходи по 8 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Віджимання",
            description: "Віджимання від стіни: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом на біцепс",
            description: "Підйом гантелей на біцепс сидячи (2-3 кг): 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Присідання",
            description: "Присідання без ваги: 3 підходи по 12 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Планка",
            description: "Планка на колінах: 3 підходи по 20 секунд.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тяга гантелей",
            description: "Тяга гантелей до пояса (2-4 кг): 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вбік: 3 підходи по 12 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 10 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Зворотні віджимання",
            description: "Зворотні віджимання від лавки: 3 підходи по 8 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Легка йога",
            description: "Легка йога (сонячний привіт): 3 підходи по 5 повторень.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Жим гантелей лежачи",
            description: "Жим гантелей лежачи (4-6 кг): 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Віджимання",
            description: "Віджимання від колін: 3 підходи по 12 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом на біцепс",
            description: "Підйом гантелей на біцепс стоячи (3-5 кг): 3 підходи по 12 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Присідання",
            description: "Присідання з гантелями (4-6 кг): 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Планка",
            description: "Планка: 3 підходи по 30 секунд.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тяга в нахилі",
            description: "Тяга гантелей в нахилі (4-6 кг): 3 підходи по 12 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами вперед: 3 підходи по 12 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні лежачи: 3 підходи по 15 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Зворотні віджимання",
            description: "Зворотні віджимання від лавки: 3 підходи по 10 повторень.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Випади",
            description: "Випади з гантелями (3-5 кг): 3 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Жим лежачи",
            description: "Жим штанги лежачи (20-30 кг): 4 підходи по 8 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Віджимання",
            description: "Віджимання: 4 підходи по 12 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом на біцепс",
            description: "Підйом штанги на біцепс стоячи (14-20 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Присідання",
            description: "Присідання зі штангою (20-30 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Планка",
            description: "Планка з підйомом ноги: 4 підходи по 45 секунд.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тяга в нахилі",
            description: "Тяга штанги в нахилі (20-30 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами назад: 4 підходи по 15 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні вису: 4 підходи по 12 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Зворотні віджимання",
            description: "Зворотні віджимання від лавки: 4 підходи по 12 повторень.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Випади",
            description: "Випади зі штангою (15-25 кг): 4 підходи по 10 повторень на кожну ногу.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Жим лежачи",
            description: "Жим штанги лежачи (30-40 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Віджимання",
            description: "Віджимання на брусах: 4 підходи по 12 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом на біцепс",
            description: "Підйом штанги на біцепс стоячи (20-25 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Присідання",
            description: "Присідання зі штангою (30-40 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Планка",
            description: "Планка з підйомом ноги: 4 підходи по 1 хвилині.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тяга в нахилі",
            description: "Тяга штанги в нахилі (30-40 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами назад: 4 підходи по 15 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні вису: 4 підходи по 15 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Зворотні віджимання",
            description: "Зворотні віджимання від лавки з вагою (10-15 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Випади",
            description: "Випади зі штангою (25-30 кг): 4 підходи по 12 повторень на кожну ногу.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Жим лежачи",
            description: "Жим штанги лежачи (40-50 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Віджимання",
            description: "Віджимання на брусах: 4 підходи по 12 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом на біцепс",
            description: "Підйом штанги на біцепс стоячи (25-30 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Присідання",
            description: "Присідання зі штангою (40-50 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Планка",
            description: "Планка з підйомом ноги: 4 підходи по 1 хвилині.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тяга в нахилі",
            description: "Тяга штанги в нахилі (40-50 кг): 4 підходи по 12 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Махи ногами",
            description: "Махи ногами назад: 4 підходи по 15 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Підйом ніг",
            description: "Підйом ніг у положенні вису: 4 підходи по 15 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Зворотні віджимання",
            description: "Зворотні віджимання від лавки з вагою (15-20 кг): 4 підходи по 10 повторень.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Випади",
            description: "Випади зі штангою (30-35 кг): 4 підходи по 12 повторень на кожну ногу.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
          }
];

const diets = [
    {
        name: "Парові овочі",
            description: "Парові овочі (броколі, цвітна капуста, морква).",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Гречка або вівсянка",
            description: "Гречка або вівсянка на воді з додаванням ягід або фруктів.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Омлет",
            description: "Омлет із печерицями та зеленню.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Шоколад",
            description: "Шматочок темного шоколаду (70% какао) як десерт.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Хлібці",
            description: "Цільнозернові хлібці або хліб з маслом із горіхів.",
            bmiCategory: "Severely underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Омлет",
            description: "Омлет із двох яєць з овочами (помідори, шпинат, перець).",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Парові овочі",
            description: "Парові овочі (броколі, цвітна капуста, морква).",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Гречана каша",
            description: "Гречана каша з гарбузом і додаванням горіхів.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Йогурт",
            description: "Нежирний йогурт або сир із додаванням горіхів або меду.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Салат",
            description: "Салат із тунцем та авокадо.",
            bmiCategory: "Underweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Фарширований перець",
            description: "Фарширований перець (фарш з індички з овочами).",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Салат",
            description: "Салат зі свіжих овочів.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Курятина",
            description: "Куряча грудка (або інша магерая м'ясна чи рибна продукція) запечена з травами.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Філе лосося",
            description: "Парове філе лосося із запеченими овочами (цвітна капуста, брюссельська капуста, морква).",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Запіканка",
            description: "Сирна запіканка з ягодами.",
            bmiCategory: "Normal weight",
            forWeightLoss: true,
            forWeightGain: false,

        },
        {
            name: "Салат",
            description: "Салат зі свіжих овочів.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Тушкована курятина",
            description: "Тушкована куряча грудка з овочами (броколі, морква, перець) у томатному соусі.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Креветки на грилі",
            description: "Креветки на грилі з салатом з авокадо та помідорів.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Котлети",
            description: "Котлети з індички з тушкованими овочами.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Риба",
            description: "Риба (лосось, тріска та ін.) запечена з овочами або салатом.",
            bmiCategory: "Overweight",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Йогурт",
            description: "Нежирний йогурт або сир із додаванням горіхів або меду.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Омлет",
            description: "Омлет із двох яєць з овочами (помідори, шпинат, перець).",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Тушковані овочі",
            description: "Тушковані овочі (кабачки, баклажани, помідори) із зеленню і часником.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Курятина",
            description: "Куряча грудка (або інша магерая м'ясна чи рибна продукція) запечена з травами.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Салат",
            description: "Салат зі свіжих овочів з оливковою олією і лимонним соком.",
            bmiCategory: "Obese",
            forWeightLoss: true,
            forWeightGain: false,
        },
        {
            name: "Омлет",
            description: "Омлет із тріскою та овочами.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Авокадо тост",
            description: "Авокадо тост з яйцем-пашот.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Сир",
            description: "Сир з фруктами та медом.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Гречана каша",
            description: "Гречана каша з додаванням кокосового молока та меду.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Йогурт",
            description: "Грецький йогурт з медом і горіхами.",
            bmiCategory: "Severely underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Вівсянка",
            description: "Вівсянка з додаванням банана, горіхів і меду.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Хумус",
            description: "Хумус з овочевими паличками.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Млинці",
            description: "Млинці з геркулесового борошна з додаванням банана і горіхів.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Омлет",
            description: "Омлет із лососем і шпинатом.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Фарширований перець",
            description: "Фарширований перець із рисом і фаршем з індички.",
            bmiCategory: "Underweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Паста",
            description: "Паста з куркою, вершками та шпинатом.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Сендвіч",
            description: "Білковий сендвіч із куркою, авокадо та овочами.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Гречана каша",
            description: "Гречана каша з додаванням кисломолочного сиру та сухофруктів.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Локшина",
            description: "Локшина рамен із креветками, овочами та соусом теріякі.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Протеїновий коктейль",
            description: "Протеїновий коктейль з какао та вівсяним молоком.",
            bmiCategory: "Normal weight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Рис із фаршем",
            description: "Рис із тушкованим яловичим фаршем та овочами.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Тріска в духовці",
            description: "Тріска в духовці з картопляним пюре та зеленим горошком.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Курятина",
            description: "Куряча грудка з кіноа та овочами.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Стейк",
            description: "Стейк із яловичини з локшиною та зеленим горошком.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Білковий коктейль",
            description: "Білковий коктейль із додаванням горіхів і меду.",
            bmiCategory: "Overweight",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Стейк",
            description: "Стейк з індички з печеними овочами та коричневим рисом.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Курячі крильця",
            description: "Курячі крильця в барбекю соусі з картопляним пюре та зеленню.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Стейк",
            description: "Стейк із тунця з картопляним гратеном і овочевим салатом.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Лосось",
            description: "Лосось на грилі з солодкою картоплею та спаржею.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
        },
        {
            name: "Гречана каша",
            description: "Гречана каша з додаванням кокосового молока та меду.",
            bmiCategory: "Obese",
            forWeightLoss: false,
            forWeightGain: true,
      }
];

const seedDatabase = async () => {
    try {
        await Exercise.deleteMany({});
        await Diet.deleteMany({});

        await Exercise.insertMany(exercises);
        await Diet.insertMany(diets);

        console.log('Database seeded successfully');
    } catch (error) {
        console.error('Error seeding database:', error);
    } finally {
        mongoose.connection.close();
    }
};

seedDatabase();
